const usersData = [{
    TasksList: "Samppa Nori",
    StartDate: "2012/01/01",
    DeliverDate: "Member",
    status: "Active",
},
{
    TasksList: "Estavan Lykos",
    StartDate: "2012/02/01",
    DeliverDate: "Staff",
    status: "Banned",
},
{
    TasksList: "Chetan Mohamed",
    StartDate: "2012/02/01",
    DeliverDate: "Admin",
    status: "Inactive",
},
{
    TasksList: "Derick Maximinus",
    StartDate: "2012/03/01",
    DeliverDate: "Member",
    status: "Pending",
},
{
    TasksList: "Friderik Dávid",
    StartDate: "2012/01/21",
    DeliverDate: "Staff",
    status: "Active",
},
{
    TasksList: "Yiorgos Avraamu",
    StartDate: "2012/01/01",
    DeliverDate: "Member",
    status: "Active",
},
{
    TasksList: "Avram Tarasios",
    StartDate: "2012/02/01",
    DeliverDate: "Staff",
    status: "Banned",
    _classes: "table-danger",
},
{
    TasksList: "Quintin Ed",
    StartDate: "2012/02/01",
    DeliverDate: "Admin",
    status: "Inactive",
},
{
    TasksList: "Enéas Kwadwo",
    StartDate: "2012/03/01",
    DeliverDate: "Member",
    status: "Pending",
},
{
    TasksList: "Agapetus Tadeáš",
    StartDate: "2012/01/21",
    DeliverDate: "Staff",
    status: "Active",
},
{
    TasksList: "Carwyn Fachtna",
    StartDate: "2012/01/01",
    DeliverDate: "Member",
    status: "Active",
    _classes: "table-success",
},
{
    TasksList: "Nehemiah Tatius",
    StartDate: "2012/02/01",
    DeliverDate: "Staff",
    status: "Banned",
},
{
    TasksList: "Ebbe Gemariah",
    StartDate: "2012/02/01",
    DeliverDate: "Admin",
    status: "Inactive",
},
{
    TasksList: "Eustorgios Amulius",
    StartDate: "2012/03/01",
    DeliverDate: "Member",
    status: "Pending",
},
{
    TasksList: "Leopold Gáspár",
    StartDate: "2012/01/21",
    DeliverDate: "Staff",
    status: "Active",
},
{
    TasksList: "Pompeius René",
    StartDate: "2012/01/01",
    DeliverDate: "Member",
    status: "Active",
},
{
    TasksList: "Paĉjo Jadon",
    StartDate: "2012/02/01",
    DeliverDate: "Staff",
    status: "Banned",
},
{
    TasksList: "Micheal Mercurius",
    StartDate: "2012/02/01",
    DeliverDate: "Admin",
    status: "Inactive",
},
{
    TasksList: "Ganesha Dubhghall",
    StartDate: "2012/03/01",
    DeliverDate: "Member",
    status: "Pending",
},
{
    TasksList: "Hiroto Šimun",
    StartDate: "2012/01/21",
    DeliverDate: "Staff",
    status: "Active",
},
{
    TasksList: "Vishnu Serghei",
    StartDate: "2012/01/01",
    DeliverDate: "Member",
    status: "Active",
},
{
    TasksList: "Zbyněk Phoibos",
    StartDate: "2012/02/01",
    DeliverDate: "Staff",
    status: "Banned",
},
{
    TasksList: "Einar Randall",
    StartDate: "2012/02/01",
    DeliverDate: "Admin",
    status: "Inactive",
    _classes: "table-danger",
},
{
    TasksList: "Félix Troels",
    StartDate: "2012/03/21",
    DeliverDate: "Staff",
    status: "Active",
},
{
    TasksList: "Aulus Agmundr",
    StartDate: "2012/01/01",
    DeliverDate: "Member",
    status: "Pending",
},
];

export default usersData;